### ISSUE TITLE
Fix "Created" date

### ISSUE THREAD

**Issue by melaniemai** [rymandn/SeniorCapstoneProject-CS5001#8]
Last time I saw the exams table, there was an example exam already created and after a few days, I logged back on and saw the "Created" date was the current date, not the date from a few days ago, which isn't right.

**Comment by conleyrj** [comment]
I think this is because the Test data we were using was creating a new exam each time the page was accessed. When a new exam is created is uses the current date at that moment. I created several exams Tuesday and they still show as created Tuesday in the table. I have attached the exam table I am viewing and I recommend closing this bug 

<img width="773" alt="image" src="https://user-images.githubusercontent.com/58665455/225698551-b829e8bb-9a11-44da-ba94-03d3638ddc44.png">
